///*
// * To change this license header, choose License Headers in Project Properties.
// * To change this template file, choose Tools | Templates
// * and open the template in the editor.
// */
//package frontend;
//
//import controllers.Controller;
//import controllers.PedidoCtrl;
//import controllers.ProdutoCtrl;
//import controllers.VendedorCtrl;
//import dao.ClienteDao;
//import dao.PedidoDao;
//import dao.ProdutoDao;
//import dao.VendedorDao;
//import database.DatabaseConnection;
//import facade.PedidoFacade;
//import java.sql.SQLException;
//import java.util.ArrayList;
//import java.util.Date;
//import java.util.logging.Level;
//import java.util.logging.Logger;
//import javax.swing.JOptionPane;
//import javax.swing.table.DefaultTableModel;
//import models.Cliente;
//import models.Pedido;
//import models.Produto;
//import models.Vendedor;
//
///**
// *
// * @author marco
// */
//public class RealizarPedido extends javax.swing.JFrame {
//
//    /**
//     * Creates new form RealizarPedido
//     */
//    public RealizarPedido() {
//        initComponents();
//    }
//
//    /**
//     * This method is called from within the constructor to initialize the form.
//     * WARNING: Do NOT modify this code. The content of this method is always
//     * regenerated by the Form Editor.
//     */
//    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        produtoCombobox = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        vendedorCombobox = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        clienteCombobox = new javax.swing.JComboBox<>();
        btnSalvarPedido = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        pedidoTabela = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        btnRemoverPedido = new javax.swing.JButton();
        quantidadeInput = new javax.swing.JTextField();
        valorInput = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("Realizar Pedido");

        jLabel2.setText("Produto");

        produtoCombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setText("Vendedor");

        vendedorCombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setText("Cliente");

        clienteCombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        clienteCombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clienteComboboxActionPerformed(evt);
            }
        });

        btnSalvarPedido.setText("Salvar");
        btnSalvarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarPedidoActionPerformed(evt);
            }
        });

        pedidoTabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Data", "Observação", "Cliente", "Vendedor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(pedidoTabela);

        jLabel5.setText("Pedidos");

        btnRemoverPedido.setText("Remover");
        btnRemoverPedido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRemoverPedidoMouseClicked(evt);
            }
        });

        quantidadeInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantidadeInputActionPerformed(evt);
            }
        });

        valorInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valorInputActionPerformed(evt);
            }
        });

        jLabel6.setText("Valor");

        jLabel7.setText("Quantidade");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(330, 330, 330))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(clienteCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2)
                            .addComponent(produtoCombobox, 0, 295, Short.MAX_VALUE)
                            .addComponent(jLabel3)
                            .addComponent(vendedorCombobox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(valorInput, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(quantidadeInput, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)))
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 635, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(btnSalvarPedido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRemoverPedido)
                .addGap(289, 289, 289))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(produtoCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(quantidadeInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(valorInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(vendedorCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clienteCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRemoverPedido)
                    .addComponent(btnSalvarPedido))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clienteComboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clienteComboboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clienteComboboxActionPerformed

    private void btnSalvarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarPedidoActionPerformed

        String produtoItem = (String) produtoCombobox.getSelectedItem();
        String vendedorItem = (String) vendedorCombobox.getSelectedItem();
        String clienteItem = (String) clienteCombobox.getSelectedItem();

        Double valorPedidoProduto = 0.00;
        int quantidade = 0;
        if (valorInput.getText().equals("") || quantidadeInput.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Por favor informe os valores corretos!");
            return;
        } else {
            valorPedidoProduto = Double.parseDouble(valorInput.getText());
            quantidade = Integer.parseInt(quantidadeInput.getText());
        }

        int codigoProduto = Character.getNumericValue(produtoItem.charAt(0));
        int codigoVendedor = Character.getNumericValue(vendedorItem.charAt(0));
        int codigoCliente = Character.getNumericValue(clienteItem.charAt(0));

        try {
            ProdutoCtrl produtoController = new ProdutoCtrl();
            Produto produto = produtoController.recover(codigoProduto);

            VendedorCtrl vendedorController = new VendedorCtrl();
            Vendedor vendedor = vendedorController.recover(codigoVendedor);

            Controller clienteController = new Controller();
            Cliente cliente = clienteController.recover(codigoCliente);

            Pedido pedido = new Pedido();
            pedido.setPed_data(new Date());
            pedido.setPed_observacao("Compra do produto  " + produto.getProd_descricao() + " do vendedor " + vendedor.getVend_nome() + " na data " + pedido.getPed_data());
            pedido.setPed_cod_cliente(cliente.getCli_codigo());
            pedido.setPed_cod_vendedor(vendedor.getVend_codigo());

            PedidoCtrl pedidoController = new PedidoCtrl();
            if (produto.getProd_saldo() <= 0) {
                JOptionPane.showMessageDialog(this, "Não há produto no Estoque!");
                return;
            }
            pedidoController.criarPedido(cliente, vendedor, pedido, produto, valorPedidoProduto, quantidade);
            this.preencherTabela();
            valorInput.setText("");
            quantidadeInput.setText("");
        } catch (Exception err) {
            System.err.println("Erro ao salvar o pedido" + err.getMessage());
        }
    }//GEN-LAST:event_btnSalvarPedidoActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            this.preencherComboboxProduto();
            this.preencherComboboxVendedor();
            this.preencherComboboxCliente();

            this.preencherTabela();
        } catch (SQLException ex) {
            Logger.getLogger(RealizarPedido.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_formWindowOpened

    private void btnRemoverPedidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRemoverPedidoMouseClicked
        int[] linhas = pedidoTabela.getSelectedRows();
        javax.swing.table.DefaultTableModel padrao = (javax.swing.table.DefaultTableModel) pedidoTabela.getModel();
        for (int i = 0; i < linhas.length; i++) {
            String codigoPedido = String.valueOf(padrao.getValueAt(linhas[i], 0));
            padrao.removeRow(linhas[i]);

            int cod = Integer.parseInt(codigoPedido);

            try {
                PedidoCtrl pedidoCtrl = new PedidoCtrl();
                Pedido pedido = pedidoCtrl.recover(cod);
                PedidoFacade pedidoFacade = new PedidoFacade();
                pedidoFacade.desfazerPedido(pedido);
                JOptionPane.showMessageDialog(this, "Pedido removido com sucesso!");
            } catch (SQLException ex) {
                Logger.getLogger(RealizarPedido.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_btnRemoverPedidoMouseClicked

    private void quantidadeInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantidadeInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantidadeInputActionPerformed

    private void valorInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valorInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valorInputActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RealizarPedido.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RealizarPedido.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RealizarPedido.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RealizarPedido.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RealizarPedido().setVisible(true);
            }
        });
    }

    public void preencherComboboxProduto() throws SQLException {
        ProdutoDao dao = new ProdutoDao();
        ArrayList<Produto> produtos = dao.recoverAll();
        produtoCombobox.removeAllItems();
        for (int i = 0; i < produtos.size(); i++) {
            produtoCombobox.addItem(produtos.get(i).toString());
        }
    }

    public void preencherComboboxVendedor() throws SQLException {
        VendedorDao dao = new VendedorDao();

        ArrayList<Vendedor> vendedores = dao.recoverAll();
        vendedorCombobox.removeAllItems();
        for (int i = 0; i < vendedores.size(); i++) {
            vendedorCombobox.addItem(vendedores.get(i).toString());
        }
    }

    public void preencherComboboxCliente() throws SQLException {
        ClienteDao dao = new ClienteDao();

        ArrayList<Cliente> clientes = dao.recoverAll();
        clienteCombobox.removeAllItems();
        for (int i = 0; i < clientes.size(); i++) {
            clienteCombobox.addItem(clientes.get(i).toString());
        }
    }

    public void preencherTabela() throws SQLException {
        DefaultTableModel padrao = (DefaultTableModel) pedidoTabela.getModel();
        padrao.setNumRows(0);

        PedidoCtrl pedidoController = new PedidoCtrl();
        String[][] dados = pedidoController.recoverAll();

        for (int i = 0; i < dados.length; i++) {
            padrao.addRow(dados[i]);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRemoverPedido;
    private javax.swing.JButton btnSalvarPedido;
    private javax.swing.JComboBox<String> clienteCombobox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable pedidoTabela;
    private javax.swing.JComboBox<String> produtoCombobox;
    private javax.swing.JTextField quantidadeInput;
    private javax.swing.JTextField valorInput;
    private javax.swing.JComboBox<String> vendedorCombobox;
    // End of variables declaration//GEN-END:variables
}
